export const AgentPermissionValidatorAbi = [
  {
    type: "function",
    name: "onInstall",
    inputs: [{ name: "data", type: "bytes", internalType: "bytes" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "onUninstall",
    inputs: [{ name: "data", type: "bytes", internalType: "bytes" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "validateUserOp",
    inputs: [
      {
        name: "userOp",
        type: "tuple",
        internalType: "struct PackedUserOperation",
        components: [
          { name: "sender", type: "address", internalType: "address" },
          { name: "nonce", type: "uint256", internalType: "uint256" },
          { name: "initCode", type: "bytes", internalType: "bytes" },
          { name: "callData", type: "bytes", internalType: "bytes" },
          { name: "accountGasLimits", type: "bytes32", internalType: "bytes32" },
          { name: "preVerificationGas", type: "uint256", internalType: "uint256" },
          { name: "gasFees", type: "bytes32", internalType: "bytes32" },
          { name: "paymasterAndData", type: "bytes", internalType: "bytes" },
          { name: "signature", type: "bytes", internalType: "bytes" },
        ],
      },
      { name: "userOpHash", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addAgent",
    inputs: [
      { name: "agent", type: "address", internalType: "address" },
      {
        name: "policy",
        type: "tuple",
        internalType: "struct AgentPolicy",
        components: [
          { name: "allowedTargets", type: "address[]", internalType: "address[]" },
          { name: "allowedSelectors", type: "bytes4[]", internalType: "bytes4[]" },
          { name: "maxAmountPerTx", type: "uint256", internalType: "uint256" },
          { name: "dailyLimit", type: "uint256", internalType: "uint256" },
          { name: "weeklyLimit", type: "uint256", internalType: "uint256" },
          { name: "validAfter", type: "uint48", internalType: "uint48" },
          { name: "validUntil", type: "uint48", internalType: "uint48" },
          { name: "active", type: "bool", internalType: "bool" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "removeAgent",
    inputs: [{ name: "agent", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getPolicy",
    inputs: [
      { name: "account", type: "address", internalType: "address" },
      { name: "agent", type: "address", internalType: "address" },
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct AgentPolicy",
        components: [
          { name: "allowedTargets", type: "address[]", internalType: "address[]" },
          { name: "allowedSelectors", type: "bytes4[]", internalType: "bytes4[]" },
          { name: "maxAmountPerTx", type: "uint256", internalType: "uint256" },
          { name: "dailyLimit", type: "uint256", internalType: "uint256" },
          { name: "weeklyLimit", type: "uint256", internalType: "uint256" },
          { name: "validAfter", type: "uint48", internalType: "uint48" },
          { name: "validUntil", type: "uint48", internalType: "uint48" },
          { name: "active", type: "bool", internalType: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isModuleType",
    inputs: [{ name: "typeId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "pure",
  },
] as const;
